---
  email: email@mail.com
  password: password

  vehicle: Mitsubishi Evolution
  must-contain: 
    - evo
  dont-contain: 
    - rear
    - front
    - trunk
    - hood
  locations:
    - portland
    - la
  daysSinceListed: 7
  sortBy: creation_time_descend
  